In [2]:
import numpy as np
matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])
sum_matrix=matrix1+matrix2
print("matrix1:\n",matrix1)
print("\nmatrix2:\n",matrix2)
print("\n sum of matrix:\n",sum_matrix)


matrix1:
 [[1 2]
 [3 4]]

matrix2:
 [[5 6]
 [7 8]]

 sum of matrix:
 [[ 6  8]
 [10 12]]
